Implemented update user functionality
TinelValentin/SlotsApp pull request #15
Opened 2022-11-01 12:54 UTC by Sorin37

2022-11-01 19:42 UTC, BrassoiCatalin approved these changes

2022-11-01 19:42 UTC, BrassoiCatalin commented on Backend/Backend/Interfaces/IUserService.cs
> +        Task<bool> Create(User user);
You can leave no spaces between properties imo.

2022-11-08 13:00 UTC, TinelValentin approved these changes

2022-11-14 14:33 UTC, BrassoiCatalin approved these changes

2022-11-14 14:34 UTC, TinelValentin commented on Backend/Backend/Controllers/UserController.cs
>          public async Task<IActionResult> Create([FromBody] User user)
Why there is no validation on create?

2022-11-14 14:50 UTC, BrassoiCatalin approved these changes

2022-11-14 14:50 UTC, TinelValentin requested changes

2022-11-14 14:50 UTC, TinelValentin commented on Backend/Backend/Controllers/UserController.cs
> +
You need to add validation for security number and email.

2022-11-14 15:20 UTC, BrassoiCatalin approved these changes

2022-11-14 15:21 UTC, TinelValentin approved these changes

2022-11-14 15:21 UTC, merged