Finished Login design
TinelValentin/SlotsApp pull request #20
Opened 2022-11-08 18:04 UTC by TinelValentin

2022-11-11 07:05 UTC, BrassoiCatalin approved these changes

2022-11-14 14:25 UTC, Sorin37 requested changes

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +            <GradientStop Color="#802525"  Offset="0.0"/>
Two spaces between Color and Offset

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +                    Center="205,0"
no space after comma

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +                                                            Offset="0.0"/>
ugly indentation

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +            <Grid HeightRequest="380" WidthRequest="340" >
extra space before tag end

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +                <Image Source ="user.png" WidthRequest="100" HorizontalOptions="Center" Grid.Row="0" Margin="0,-50,0,0"/>
no space after comma

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +                        PlaceholderColor="DarkGray" >
extra space before end of tag

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +        <Button  WidthRequest="180" HeightRequest="50" Margin="0,-40,0,0" HorizontalOptions="Center"
no space after comma

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +        <Button WidthRequest="200" HeightRequest="50" Margin="0,0,0,0" HorizontalOptions="Center"
no space after comma

2022-11-14 14:25 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignInView.xaml
> +    </StackLayout>
both stack layouts are on the same column

2022-11-14 15:31 UTC, merged