UI blackjack
TinelValentin/SlotsApp pull request #25
Opened 2022-11-21 17:05 UTC by BrassoiCatalin

Made it so you can bet an amount in Blackjack game.

2022-11-21 17:08 UTC, TinelValentin approved these changes

2022-11-21 17:11 UTC, Sorin37 requested changes

2022-11-21 17:11 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/ViewModel/BlackjackViewModel.cs
> +
Unnecessary new line

2022-11-21 17:15 UTC, TinelValentin approved these changes

2022-11-21 19:45 UTC, Sorin37 requested changes

2022-11-21 19:45 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/Model/Player.cs
> +
Unnecessary new line

2022-11-21 19:45 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/Model/Player.cs
> +        public Player(string name, int bankroll, int totalbet = 0, int totalwin = 0, int betAmount = 0)
the name of the parameters do not respect the camel case regulations

2022-11-21 19:45 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/ViewModel/BlackjackViewModel.cs
> +             "c01", "c02", "c03", "c04", "c05", "c06", "c07", "c08", "c09", "c10", "c11", "c12", "d13", "d01", "d02", "d03", "d04", "d05", "d06", "d07", "d08", "d09", "d10", "d11", "d12", "d13", "h01
I suggest that you would put the strings on separate lines like so:
c01, c02...
d01, d02...
and so on

2022-11-21 19:45 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/ViewModel/BlackjackViewModel.cs
> +            for (int i = 0; i < INITIALDEAL; i++)
why is INITIALDEAL all caps?

2022-11-21 19:45 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/ViewModel/BlackjackViewModel.cs
> +
Unecessary new line

2022-11-21 19:45 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/ViewModel/BlackjackViewModel.cs
> +
Unnecessary new line

2022-11-25 10:45 UTC, Sorin37 approved these changes
Lgtm

2022-11-25 10:45 UTC, merged