Crash game
TinelValentin/SlotsApp pull request #32
Opened 2022-12-03 15:51 UTC by TinelValentin

Any comment about refactoring the class CrashView.xaml.cs will be ignored

2022-12-03 17:01 UTC, BrassoiCatalin requested changes

2022-12-03 17:01 UTC, BrassoiCatalin commented on SevenSlots/SevenSlots/SevenSlots/View/App.xaml.cs
> +
Why so many white spaces?

2022-12-05 12:45 UTC, BrassoiCatalin approved these changes

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml
> +
empty new line

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml
> +                        <Label Style="{StaticResource MultiplierLabel}" Text="{Binding MultiplierLabelValues[2], StringFormat='{0}.0x'}"></Label>
brake attributes on multiple lines

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml
> +                <StackLayout x:Name="PlaneCrashedText" IsVisible="false" Margin="20,-200,0,0">
no space after comma

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml
> +
empty new line

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml.cs
> +            1.26m,1.25m
no space after comma

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml.cs
> +            1,2,4
no space after comma

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml.cs
> +            0,1,2
no space after comma

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml.cs
> +                            1,2,4
no space after comma

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml.cs
> +                            0,1,2
no space after comma

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml.cs
> +#pragma warning disable CS4014 // This call is not awaited because we want the animation to run while the multiplier increases
fix indentation

2022-12-05 12:51 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/CrashView.xaml.cs
> +#pragma warning restore CS4014
fix indentation

2022-12-05 13:02 UTC, BrassoiCatalin approved these changes

2022-12-05 13:16 UTC, Sorin37 approved these changes

2022-12-05 13:16 UTC, merged