Fixed Login pop up
TinelValentin/SlotsApp pull request #34
Opened 2022-12-03 17:29 UTC by TinelValentin

2022-12-03 17:30 UTC, TinelValentin commented
Also fixed a bug where the styles where not always used in sign up view

2022-12-03 17:34 UTC, BrassoiCatalin approved these changes

2022-12-05 12:54 UTC, Sorin37 requested changes

2022-12-05 12:54 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/LoginErrorPopup.xaml
> +                     Margin="20"
align the attributes accordingly

2022-12-05 12:54 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignUpView.xaml
> +                                >
inconsistent tag ending

2022-12-05 12:54 UTC, Sorin37 commented on SevenSlots/SevenSlots/SevenSlots/View/SignUpView.xaml
>                                           InvalidStyle="{StaticResource InvalidStyle}">
this can go on the same line with the tag

2022-12-05 13:05 UTC, TinelValentin commented on SevenSlots/SevenSlots/SevenSlots/View/LoginErrorPopup.xaml
> +                     Margin="20"
But it is alligned

2022-12-05 13:15 UTC, Sorin37 approved these changes

2022-12-05 13:15 UTC, merged